#ifndef __INCLUDED_SEAT_Error____H
#define __INCLUDED_SEAT_Error____H



#define ERR_SEAT_SUCCESSFUL						0
#define ERR_SEAT_NOT_INITIALIZED				-1
#define ERR_SEAT_NO_IMPLEMENT					-2
#define ERR_SEAT_INVALID_PARAMETER				-3
#define ERR_SEAT_WRONG_AT_TYPE					-4
#define ERR_SEAT_INVALID_HANDLE					-5
#define ERR_SEAT_WRONG_HANDLE					-6

#define ERR_SEAT_RECOGNIZER_NO_SIGNAL			-7
#define ERR_SEAT_RECOGNIZER_NOT_ENOUGHSIGNAL	-8
#define ERR_SEAT_RECOGNIZER_NO_HEAD_OR_TAIL		-9
#define ERR_SEAT_RECOGNIZER_NO_EXPIRES			-10
#define ERR_SEAT_RECOGNIZER_WRONG_ECC			-11

#define ERR_SEAT_CREATE_FAIL					-12




#endif //// #ifndef __INCLUDED_SEAT_Error____H